// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scan_request.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScanRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	From                 uint64   `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   uint64   `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c75b0c589eef47, []int{0}
}

func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ScanRequest) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *ScanRequest) GetTo() uint64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *ScanRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*ScanRequest)(nil), "protobuf.ScanRequest")
}

func init() { proto.RegisterFile("scan_request.proto", fileDescriptor_e4c75b0c589eef47) }

var fileDescriptor_e4c75b0c589eef47 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4e, 0x4e, 0xcc,
	0x8b, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0xe1, 0x5c, 0xdc, 0xc1, 0xc9, 0x89, 0x79, 0x41, 0x10, 0x69,
	0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53,
	0x48, 0x88, 0x8b, 0x25, 0xad, 0x28, 0x3f, 0x57, 0x82, 0x49, 0x81, 0x51, 0x83, 0x25, 0x08, 0xcc,
	0x16, 0xe2, 0xe3, 0x62, 0x2a, 0xc9, 0x97, 0x60, 0x06, 0x8b, 0x30, 0x95, 0xe4, 0x83, 0xd4, 0x94,
	0x54, 0x16, 0xa4, 0x4a, 0xb0, 0x80, 0xb5, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0x2b, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x9c, 0x48, 0x4b, 0xa3, 0x7f, 0x00, 0x00, 0x00,
}
